server:
  addr: 0.0.0.0:8080
  debug: false
  timeout:
    read-seconds: 15
    write-seconds: 20

db:
  host: db
  user: postgres
  password: pismo
  name: pismo

operation_types:
  COMPRA_A_VISTA: "-"
  COMPRA_PARCELADA: "-"
  SAQUE: "-"
  PAGAMENTO: "+"
  LIMITE_DE_CREDITO: "+"
